### ISSUE TITLE
Error running cmd: quire template epub

### ISSUE THREAD

**Issue by emptyhut** [thegetty/quire#123]
working in root directory of project. Command, "quire template epub" gives following:

TypeError: e.downloadTemplate is not a function
    at e.value (/opt/local/lib/node_modules/@thegetty/quire-cli/bin/index.js:2:50915)
    at emit (events.js:315:20)
    at Command.<anonymous> (/opt/local/lib/node_modules/@thegetty/quire-cli/bin/index.js:2:123877)
    at Command.listener (/opt/local/lib/node_modules/@thegetty/quire-cli/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/opt/local/lib/node_modules/@thegetty/quire-cli/node_modules/commander/index.js:892:12)
    at Command.parse (/opt/local/lib/node_modules/@thegetty/quire-cli/node_modules/commander/index.js:642:21)
    at /opt/local/lib/node_modules/@thegetty/quire-cli/bin/index.js:2:124163
    at Object.<anonymous> (/opt/local/lib/node_modules/@thegetty/quire-cli/bin/index.js:2:124770)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

**Comment by geealbers** [comment]
Thanks for bringing this to our attention. Our development team will work on a fix. In the meantime, here's the file that would have been generated had `quire template epub` worked. It just goes in the root of your project as `epub/template.xhtml`:

[epub.zip](https://github.com/thegetty/quire/files/6503728/epub.zip)

I'm afraid this isn't well documented though, and is much different than the rest of Quire. So let us know if there's something in particular you’re trying to do and need help with. You may also find some useful documentation with Pandoc, as that's the tool that handles Quire's EPUB output.

**Comment by geealbers** [comment]
Cross-posted to Getty Jira: [DEV-9033](https://jira.getty.edu/browse/DEV-9033).

**Comment by geealbers** [comment]
Still an issue in the last version of Quire to use Hugo (0.20.4) but it's a `wontfix` as newer versions of Quire using 11ty use a completely different EPUB architecture and don't have this issue. For users of older versions of Quire, the manual fix noted above, along with the linked file, should still suffice. Closing the issue
