### ISSUE TITLE
Theme dependencies are not installed with `quire new` on Windows

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire#50]
**Steps to reproduce:**

1. On a Windows machine, run `quire new project-name`
2. Check the `themes/default/` directory to confirm `node_modules` have been installed as part of the process, OR try to run `quire preview` in the new project.

**Expected behavior:**

A `node_modules` folder would be present, and the site would preview normally.

**Actual behavior:**

There is no `node_modules` folder, and `quire preview` throws the following error.

```
PS C:\Users\geeal> quire new test-test
Creating project...
Using starter: default
Using theme: default
Initializing git in the new project directory...
Committing starter files...
Installing dependencies. This may take a minute...
Theme and dependencies successfully installed.
Run quire preview in your project folder to view changes locally.
PS C:\Users\geeal> cd test-test
PS C:\Users\geeal\test-test> quire preview --verbose
Launching preview server
i Navigate to http://localhost:1313 to see your changes.
i Press Control+C or type "quire stop" to stop the preview.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\.bin\webpack.cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn node_modules\\.bin\\webpack.cmd',
  path: 'node_modules\\.bin\\webpack.cmd',
  spawnargs: [
    '--watch',
    '-d',
    '--progress',
    '--color',
    '--config',
    'webpack/webpack.config.dev.js'
  ]
}
PS C:\Users\geeal\test-test>
```

**Comment by geealbers** [comment]
Being tracked by Getty in Jira at: https://jira.getty.edu/browse/DEV-8262

**Comment by mwilliams8359** [comment]
Hi @geealbers !

Just wondering if you've found any workaround for this bug. I've started playing around with Quire but as I'm on a Windows machine I can't generate the preview. 
Very much appreciate your help! 
Matt


```
`PS C:\WINDOWS\system32\my-project> quire preview --verbose
Launching preview server
i Navigate to http://localhost:1313 to see your changes.
i Press Control+C or type "quire stop" to stop the preview.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\.bin\webpack.cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn node_modules\\.bin\\webpack.cmd',
  path: 'node_modules\\.bin\\webpack.cmd',
  spawnargs: [
    '--watch',
    '-d',
    '--progress',
    '--color',
    '--config',
    'webpack\\webpack.config.dev.js'
  ]
}`
```

**Comment by geealbers** [comment]
@mwilliams8359, yes, we think we have a more permanent fix, but for now try running `quire install` in your project. After that, the preview should work as expected. Let me know if not though. And can you also run `quire --version` and let me know the version number you've got installed? Thanks

**Comment by mwilliams8359** [comment]
Thanks, @geealbers !
So, it sort of worked. I was able to generate a preview using the local host, but the background wasn't pulled in as expected (see screenshot). This could be an error on my side somewhere, but just thought I should include it. Also, while looking through the code, I too experienced the issue here: https://github.com/thegetty/quire/issues/20
![Screenshot 2021-04-13 095105](https://user-images.githubusercontent.com/58611933/114590605-d4ad5700-9c3d-11eb-92b4-c1b8ce26813b.png)


I'm running v0.19.0
Thanks so much!
Matt


Here's the text:
```
Building: C:\Program Files\nodejs\node.exe C:\WINDOWS\system32\my-book\themes\default\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\WINDOWS\\system32\\my-book\\themes\\default\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.16.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\matth\.windows-build-tools\python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\matth\.windows-build-tools\python27\python.exe C:\Users\matth\.windows-build-tools\python27\python.exe
gyp verb check python version `C:\Users\matth\.windows-build-tools\python27\python.exe -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.16.1
gyp verb command install [ '14.16.1' ]
gyp verb install input version string "14.16.1"
gyp verb install installing version: 14.16.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.16.1
gyp verb build dir attempting to create "build" dir: C:\WINDOWS\system32\my-book\themes\default\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\WINDOWS\system32\my-book\themes\default\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.17763
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\WINDOWS\system32\my-book\themes\default\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\WINDOWS\system32\my-book\themes\default\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\WINDOWS\system32\my-book\themes\default\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\matth\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\WINDOWS\\system32\\my-book\\themes\\default\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\WINDOWS\\system32\\my-book\\themes\\default\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\WINDOWS\\system32\\my-book\\themes\\default\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\matth\\.node-gyp\\14.16.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\matth\\.node-gyp\\14.16.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\WINDOWS\\system32\\my-book\\themes\\default\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\matth\\.node-gyp\\14.16.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\WINDOWS\\system32\\my-book\\themes\\default\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\WINDOWS\\system32\\my-book\\themes\\default\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\matth\.node-gyp\14.16.1
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
MSBUILD : error MSB1009: Project file does not exist.
Switch: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\WINDOWS\system32\my-book\themes\default\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\WINDOWS\\system32\\my-book\\themes\\default\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\WINDOWS\system32\my-book\themes\default\node_modules\node-sass
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\matth\AppData\Roaming\npm-cache\_logs\2021-04-13T16_36_59_175Z-debug.log
√ Theme dependencies successfully installed.
√ Run quire preview to view changes locally.
PS C:\WINDOWS\system32\my-book> quire preview
Launching preview server
i Navigate to http://localhost:1313 to see your changes.
i Press Control+C or type "quire stop" to stop the preview.
10% building 0/0 modules 0 active
webpack is watching the files…

10% building 0/1 modules 1 active ...dex.js??ref--4!C:\WINDOWS\system32\my-book\themes\default\source\js\application.jsBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
```

**Comment by geealbers** [comment]
@mwilliams8359 ok, some progress I guess!

When you initially installed Quire, you at some point ran `npm install --g --production windows-build-tools` presumably. Do you remember if that seemed to have worked? I think it might be worth running that command again, and then, assuming you don't see any errors there, trying `quire install` one more time. See if we can shake something loose. The issue is that the stylesheets aren't being compiled the way they should be.

**Comment by mwilliams8359** [comment]
Hi @geealbers ,

We're all fixed! I suspect my last comment was due to user error. Everything came in fine after I switched directories from

`C:\WINDOWS\system32\projectname` 
to 
`C:\users\matth\projectname
`
Really appreciate your patience and help! Can't wait to dive in and play around with this tool. 
Thanks,
Matt

**Comment by geealbers** [comment]
Fantastic, thanks for the update @mwilliams8359!
