### ISSUE TITLE
An error is thrown when trying to run `quire epub`

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire#671]
### Before proceeding, check to make sure there isn’t an existing issue for this bug.

- [X] I have searched the existing issues and determined this is a new bug.

### Steps to reproduce

Start a new project using cli v1.0.0-rc.3 and run `quire epub`. (Not sure if you need to run `quire build` beforehand, but whether you do or don't the resulting behavior is the same.)

### Actual behavior

An error is thrown:

```
galbers@GT29043 test-rc3-lts % quire epub
file:///Users/galbers/.nvm/versions/node/v18.12.1/lib/node_modules/@thegetty/quire-cli/src/lib/epub/index.js:14
  switch (lib.toLowerCase()) {
              ^

TypeError: lib.toLowerCase is not a function
    at default (file:///Users/galbers/.nvm/versions/node/v18.12.1/lib/node_modules/@thegetty/quire-cli/src/lib/epub/index.js:14:15)
    at Command.action (file:///Users/galbers/.nvm/versions/node/v18.12.1/lib/node_modules/@thegetty/quire-cli/src/commands/epub.js:51:27)
    at Command.listener [as _actionHandler] (/Users/galbers/.nvm/versions/node/v18.12.1/lib/node_modules/@thegetty/quire-cli/node_modules/commander/lib/command.js:482:17)
    at /Users/galbers/.nvm/versions/node/v18.12.1/lib/node_modules/@thegetty/quire-cli/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/Users/galbers/.nvm/versions/node/v18.12.1/lib/node_modules/@thegetty/quire-cli/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/Users/galbers/.nvm/versions/node/v18.12.1/lib/node_modules/@thegetty/quire-cli/node_modules/commander/lib/command.js:1283:27)
    at /Users/galbers/.nvm/versions/node/v18.12.1/lib/node_modules/@thegetty/quire-cli/node_modules/commander/lib/command.js:1081:27
    at Command._chainOrCall (/Users/galbers/.nvm/versions/node/v18.12.1/lib/node_modules/@thegetty/quire-cli/node_modules/commander/lib/command.js:1177:12)
    at Command._dispatchSubcommand (/Users/galbers/.nvm/versions/node/v18.12.1/lib/node_modules/@thegetty/quire-cli/node_modules/commander/lib/command.js:1077:23)
    at Command._parseCommand (/Users/galbers/.nvm/versions/node/v18.12.1/lib/node_modules/@thegetty/quire-cli/node_modules/commander/lib/command.js:1248:19)
```

### Expected behavior

Instead, an EPUB of the project should have been generated.

### Version numbers

macoS Monterey (12.6)
Quire CLI 1.0.0-rc.3
Quire 11ty 1.0.0-rc.3
Node 18.12.1

**Comment by geealbers** [comment]
Fixed as of 1.0.0-rc.6 release of the CLI
