### ISSUE TITLE
Build error on `quire build` on `quire-11ty@1.0.0-rc.17`

### ISSUE THREAD

**Issue by cbutcosk** [thegetty/quire#907]
### Before proceeding, make sure there isn’t an existing issue for this bug.

- [X] I have searched the existing issues and determined this is a new bug.

### Expected Behavior

After starting a new project with `quire-cli@latest` and `quire-11ty@latest`, using `quire-starter-default@latest`, I expect `quire build` to produce no errors.

### Actual Behavior

A fresh project with `quire-cli@1.0.0-rc.11`, `quire-cli@1.0.0-rc.17`, `quire-starter-default@2.9.0` produces this error after figures processing:
```text
[quire] INFO	 Figures:IIIF:Manifest          Generated manifest for figure "mother-annotations"
[quire] INFO	 Figures                        Processing complete
ERROR Error: Check the dynamic attribute: `@html="component(id, image_dir)"`.
Original error message: caption is not defined
    at ModuleScript.evaluateScript (/Users/incharge/Documents/Projects/weichbild/getty-quire-pdf/quire-pdf-firststeps/quire/test-pub/node_modules/@11ty/webc/src/moduleScript.cjs:71:10)
    at async AstSerializer.evaluateAttribute (file:///Users/incharge/Documents/Projects/weichbild/getty-quire-pdf/quire-pdf-firststeps/quire/test-pub/node_modules/@11ty/webc/src/ast.js:787:21)
    at async AstSerializer.getPropContentAst (file:///Users/incharge/Documents/Projects/weichbild/getty-quire-pdf/quire-pdf-firststeps/quire/test-pub/node_modules/@11ty/webc/src/ast.js:820:17)
    at async AstSerializer.compileNode (file:///Users/incharge/Documents/Projects/weichbild/getty-quire-pdf/quire-pdf-firststeps/quire/test-pub/node_modules/@11ty/webc/src/ast.js:1152:25)
    at async AstSerializer.getChildContent (file:///Users/incharge/Documents/Projects/weichbild/getty-quire-pdf/quire-pdf-firststeps/quire/test-pub/node_modules/@11ty/webc/src/ast.js:349:56)
    at async AstSerializer.compileNode (file:///Users/incharge/Documents/Projects/weichbild/getty-quire-pdf/quire-pdf-firststeps/quire/test-pub/node_modules/@11ty/webc/src/ast.js:1226:36)
    at async AstSerializer.getChildContent (file:///Users/incharge/Documents/Projects/weichbild/getty-quire-pdf/quire-pdf-firststeps/quire/test-pub/node_modules/@11ty/webc/src/ast.js:349:56)
    at async AstSerializer.compileNode (file:///Users/incharge/Documents/Projects/weichbild/getty-quire-pdf/quire-pdf-firststeps/quire/test-pub/node_modules/@11ty/webc/src/ast.js:1226:36)
    at async AstSerializer.getChildContent (file:///Users/incharge/Documents/Projects/weichbild/getty-quire-pdf/quire-pdf-firststeps/quire/test-pub/node_modules/@11ty/webc/src/ast.js:349:56)
    at async AstSerializer.compileNode (file:///Users/incharge/Documents/Projects/weichbild/getty-quire-pdf/quire-pdf-firststeps/quire/test-pub/node_modules/@11ty/webc/src/ast.js:1226:36)
```

### Steps to Reproduce

- Install quire CLI according to install instructions
- Start a new project
- Run `quire build` in the new project

### Version Numbers

[CLI] Command 'info' called with options { debug: true }
[test-pub]
 quire-cli 1.0.0-rc.11
 quire-11ty 1.0.0-rc.17
 starter https://github.com/thegetty/quire-starter-default@2.9.0
[System]
 quire-cli 1.0.0-rc.11
 node v21.6.2
 npm 6.14.18
 os Darwin 23.3.0

**Comment by cbutcosk** [comment]
Meant to say -- AFAICT the build succeeds regardless in terms site-build contents and return code (which is also a little troubling tbh, it should stop the world and return not-0 I think?).

**Comment by Erin-Cecele** [comment]
@cbutcosk I just wanted to touch base. I just tested this issue and could not recreate it. Everything looks to be processing just fine. OK for me to close? 

[next-project]
 quire-cli 1.0.0-rc.11
 quire-11ty 1.0.0-rc.17
 starter https://github.com/thegetty/quire-starter-default@2.9.0
[System]
 quire-cli 1.0.0-rc.11
 node v18.17.0
 npm 9.6.7
 os Darwin 21.6.0

**Comment by cbutcosk** [comment]
Oh yes happy to say this can be closed @Erin-Cecele !

**Comment by Erin-Cecele** [comment]
Thank you @cbutcosk!!
