### ISSUE TITLE
Locally hosted 'video' breaks preview and build

### ISSUE THREAD

**Issue by brutaldigital** [thegetty/quire#958]
### Before proceeding, make sure there isn’t an existing issue for this bug.

- [X] I have searched the existing issues and determined this is a new bug.

### Expected Behavior

> Along with Vimeo and YouTube videos, Quire can also support video that you include directly in your project.

### Actual Behavior

Quire preview and build fails without an error message.

### Steps to Reproduce

Add figure entry following Quire v1.0 guidance:

```yaml
- id: vid-2
  poster: video-2-still.jpg
  src: my-video-file.mp4
  media_type: video
```
Run `quire preview` in Terminal

### Version Numbers

 quire-cli 1.0.0-rc.11
 quire-11ty 1.0.0-rc.16
 starter https://github.com/thegetty/quire-starter-default@2.9.0
[System]
 quire-cli 1.0.0-rc.15
 node v20.16.0
 npm 10.8.1
 os Darwin 23.6.0

### Web Browser

Chrome 129 on macOS (Sonoma)
https://whatismybrowser.com/w/NSK4TML

### Relevant Terminal/Shell Output

```shell
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] Cannot read properties of undefined (reading 'output') (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'output')
[11ty]     at get staticInlineFigureImage [as staticInlineFigureImage] (/Users/thomasscutt/GitHub/britishartstudies-26/_plugins/figures/figure/index.js:218:87)
[11ty]     at Figure.adapter (/Users/thomasscutt/GitHub/britishartstudies-26/_plugins/figures/figure/index.js:251:37)
[11ty]     at /Users/thomasscutt/GitHub/britishartstudies-26/_plugins/figures/index.js:46:42
[11ty]     at Array.map (<anonymous>)
[11ty]     at AsyncEventEmitter.<anonymous> (/Users/thomasscutt/GitHub/britishartstudies-26/_plugins/figures/index.js:46:15)
[11ty]     at async Promise.all (index 1)
[11ty]     at async Eleventy.executeBuild (/Users/thomasscutt/GitHub/britishartstudies-26/node_modules/@11ty/eleventy/src/Eleventy.js:1176:7)
[11ty]     at async Eleventy.watch (/Users/thomasscutt/GitHub/britishartstudies-26/node_modules/@11ty/eleventy/src/Eleventy.js:1014:18)
[11ty] Wrote 0 files in 0.18 seconds (v2.0.1)
```

### Supporting Information

Commenting out the `media_type` and `src` corrects the issue.

**Comment by andy-jdl** [comment]
Hey @Erin-Cecele, I wanted to share my findings with the team regarding a potential fix for this issue.

I was able to reproduce the crash using a locally hosted video and tracked the stack to `staticInlineFigureImage`.  For .mp4 files, formats are undefined in iiifConfig.formats, which causes the function to throw when accessing format.output.

Adding an early return when format is undefined prevents the function from falling through image specific logic and resolves the crash.

I was thinking we explicitly add handling video figures to `staticInlineFigureImage` either by returning a poster image when defined or short-circuiting entirely for video media (in which case returns a WARN).
